"""initial schema

Revision ID: 0308eb46727d
Revises:
Create Date: 2026-09-18 12:38:41.108163

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0308eb46727d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("application_errors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_application_errors_id"), ["id"], unique=False)

    op.create_table(
        "concept_list",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "category", "owner_id", name="_name_category_owner_id_uc"),
    )
    with op.batch_alter_table("concept_list", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_concept_list_id"), ["id"], unique=False)

    op.create_table(
        "flow_session", sa.Column("id", sa.UUID(), nullable=False), sa.Column("flow", sa.String(), nullable=True), sa.PrimaryKeyConstraint("id")
    )
    with op.batch_alter_table("flow_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_flow_session_id"), ["id"], unique=False)

    op.create_table(
        "non_omop_analytics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("database", sa.String(), nullable=True),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("sql_explanation", sa.String(), nullable=True),
        sa.Column("sql_query", sa.String(), nullable=True),
        sa.Column("exec_time_analysis", sa.Float(), nullable=True),
        sa.Column("exec_time_sql", sa.Float(), nullable=True),
        sa.Column("sql_result", sa.String(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("trace_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("non_omop_analytics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_non_omop_analytics_id"), ["id"], unique=False)

    op.create_table(
        "personalized_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("questions", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("personalized_questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_personalized_questions_id"), ["id"], unique=False)

    op.create_table(
        "preferred_coding_system",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("preferred_coding_system", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("preferred_coding_system", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_preferred_coding_system_id"), ["id"], unique=False)

    op.create_table(
        "results_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("database", sa.String(), nullable=True),
        sa.Column("contact_permission", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("sql", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "selected_databases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("databases", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("selected_databases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_selected_databases_id"), ["id"], unique=False)

    op.create_table(
        "sql_self_healing_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("user_input", sa.String(), nullable=True),
        sa.Column("query_template", sa.Text(), nullable=True),
        sa.Column("initial_query", sa.Text(), nullable=True),
        sa.Column("final_query", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("max_retries_reached", sa.Boolean(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("created_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sql_self_healing_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sql_self_healing_logs_id"), ["id"], unique=False)

    op.create_table(
        "study_descriptor",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ext_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("protocol_link", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ext_id"),
    )
    with op.batch_alter_table("study_descriptor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_study_descriptor_id"), ["id"], unique=False)

    op.create_table(
        "user_analytics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("page", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_analytics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_analytics_id"), ["id"], unique=False)

    op.create_table(
        "cohort_descriptor",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("database", sa.String(), nullable=False),
        sa.Column("database_schema", sa.String(), nullable=True),
        sa.Column("table", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=True),
        sa.Column("criteria", sa.JSON(), nullable=True),
        sa.Column("coding_system", sa.String(), nullable=True),
        sa.Column("user_concepts", sa.JSON(), nullable=True),
        sa.Column("query_template", sa.String(), nullable=True),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("explanation", sa.String(), nullable=True),
        sa.Column("covariates", sa.JSON(), nullable=True),
        sa.Column("study_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["study_descriptor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cohort_descriptor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cohort_descriptor_id"), ["id"], unique=False)

    op.create_table(
        "concept_list_revision",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("concept_list_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("database", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("concepts", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["concept_list_id"], ["concept_list.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("concept_list_id", "name", name="_concept_list_id_name_uc"),
    )
    with op.batch_alter_table("concept_list_revision", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_concept_list_revision_id"), ["id"], unique=False)

    op.create_table(
        "uncertainty_estimation_data",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("flow_session_id", sa.UUID(), nullable=True),
        sa.Column("user_email", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("database_name", sa.String(), nullable=True),
        sa.Column("user_input", sa.String(), nullable=True),
        sa.Column("final_answer", sa.String(), nullable=True),
        sa.Column("matrices", sa.JSON(), nullable=True),
        sa.Column("entropies", sa.JSON(), nullable=True),
        sa.Column("contributions", sa.JSON(), nullable=True),
        sa.Column("uncertainty_estimate", sa.String(), nullable=True),
        sa.Column("timestamp", sa.String(), nullable=True),
        sa.Column("question_index", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["flow_session_id"], ["flow_session.id"], name="flow_session_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("uncertainty_estimation_data", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_uncertainty_estimation_data_id"), ["id"], unique=False)

    op.create_table(
        "cohort_access",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("granted_by", sa.String(), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["cohort_id"], ["cohort_descriptor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cohort_id", "user_email", name="_cohort_access_cohort_user_uc"),
    )
    with op.batch_alter_table("cohort_access", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cohort_access_cohort_id"), ["cohort_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cohort_access_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cohort_access_user_email"), ["user_email"], unique=False)

    op.create_table(
        "funnel_criterion",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("query_template", sa.String(), nullable=False),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["cohort_id"], ["cohort_descriptor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cohort_id", "index", name="_cohort_id_index_uc"),
    )
    with op.batch_alter_table("funnel_criterion", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_funnel_criterion_id"), ["id"], unique=False)

    op.create_table(
        "queries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("user_email", sa.String(), nullable=True),
        sa.Column("user_input", sa.String(), nullable=True),
        sa.Column("interpretation", sa.String(), nullable=True),
        sa.Column("interpretation_index", sa.Integer(), nullable=True),
        sa.Column("answer", sa.String(), nullable=True),
        sa.Column("query_template", sa.String(), nullable=True),
        sa.Column("query_filled_preview", sa.String(), nullable=True),
        sa.Column("query_filled_search", sa.String(), nullable=True),
        sa.Column("database_name", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("cohort_id", sa.UUID(), nullable=True),
        sa.Column("flow", sa.String(), nullable=True),
        sa.Column("flow_session_id", sa.UUID(), nullable=True),
        sa.Column("uncertainty_estimation_data", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["cohort_id"], ["cohort_descriptor.id"], name="queries_cohort_id_fkey", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["flow_session_id"], ["flow_session.id"], name="flow_session_fkey", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uncertainty_estimation_data"], ["uncertainty_estimation_data.id"], name="uncertainty_estimation_data_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("queries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_queries_id"), ["id"], unique=False)

    op.create_table(
        "executed_queries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=True),
        sa.Column("database_name", sa.String(), nullable=True),
        sa.Column("sql_text", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["query_id"], ["queries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("executed_queries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_executed_queries_id"), ["id"], unique=False)

    op.create_table(
        "medical_concepts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=True),
        sa.Column("concept_name", sa.String(), nullable=True),
        sa.Column("domain_id", sa.String(), nullable=True),
        sa.Column("vocabulary", sa.JSON(), nullable=True),
        sa.Column("top_k", sa.Integer(), nullable=True),
        sa.Column("llm_filter", sa.String(), nullable=True),
        sa.Column("cosine_similarity", sa.Numeric(), nullable=True),
        sa.Column("standard_concept", sa.String(), nullable=True),
        sa.Column("database", sa.String(), nullable=True),
        sa.Column("concepts", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["query_id"], ["queries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medical_concepts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_medical_concepts_id"), ["id"], unique=False)

    op.create_table(
        "query_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=True),
        sa.Column("database_name", sa.String(), nullable=True),
        sa.Column("database_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["query_id"], ["queries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("query_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_query_results_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("query_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_query_results_id"))

    op.drop_table("query_results")
    with op.batch_alter_table("medical_concepts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medical_concepts_id"))

    op.drop_table("medical_concepts")
    with op.batch_alter_table("executed_queries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_executed_queries_id"))

    op.drop_table("executed_queries")
    with op.batch_alter_table("queries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queries_id"))

    op.drop_table("queries")
    with op.batch_alter_table("funnel_criterion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_funnel_criterion_id"))

    op.drop_table("funnel_criterion")
    with op.batch_alter_table("cohort_access", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cohort_access_user_email"))
        batch_op.drop_index(batch_op.f("ix_cohort_access_id"))
        batch_op.drop_index(batch_op.f("ix_cohort_access_cohort_id"))

    op.drop_table("cohort_access")
    with op.batch_alter_table("uncertainty_estimation_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uncertainty_estimation_data_id"))

    op.drop_table("uncertainty_estimation_data")
    with op.batch_alter_table("concept_list_revision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_concept_list_revision_id"))

    op.drop_table("concept_list_revision")
    with op.batch_alter_table("cohort_descriptor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cohort_descriptor_id"))

    op.drop_table("cohort_descriptor")
    with op.batch_alter_table("user_analytics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_analytics_id"))

    op.drop_table("user_analytics")
    with op.batch_alter_table("study_descriptor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_study_descriptor_id"))

    op.drop_table("study_descriptor")
    with op.batch_alter_table("sql_self_healing_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sql_self_healing_logs_id"))

    op.drop_table("sql_self_healing_logs")
    with op.batch_alter_table("selected_databases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_selected_databases_id"))

    op.drop_table("selected_databases")
    op.drop_table("results_feedback")
    with op.batch_alter_table("preferred_coding_system", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_preferred_coding_system_id"))

    op.drop_table("preferred_coding_system")
    with op.batch_alter_table("personalized_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_personalized_questions_id"))

    op.drop_table("personalized_questions")
    with op.batch_alter_table("non_omop_analytics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_non_omop_analytics_id"))

    op.drop_table("non_omop_analytics")
    with op.batch_alter_table("flow_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flow_session_id"))

    op.drop_table("flow_session")
    with op.batch_alter_table("concept_list", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_concept_list_id"))

    op.drop_table("concept_list")
    with op.batch_alter_table("application_errors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_application_errors_id"))

    op.drop_table("application_errors")
    # ### end Alembic commands ###
